---
- hosts: rpis
  tasks: 
    - name: "Set Default Runlevel to Multi-User.Target"
      block:
      - name: "Get Current Target/Runlevel"
        command: "systemctl get-default"
        register: result
        changed_when: False
        failed_when: result.rc != 0

      - debug:
          msg: "{{ result }}"
        when: result.changed

      - name: "Set Default Target/Runlevel"
        become: yes
        command: "systemctl set-default multi-user.target"
        register: result
        changed_when: result.stderr != ""
        failed_when: result.rc != 0

      - debug:
          msg: "{{ result }}"
        when: result.changed

- hosts: master
  tasks: 
    - name: "Get Hostname of Master"
      block:
      - command: "hostname"
        register: hostname

      - debug:
          msg: "Hostname: {{ hostname.stdout }}"

- hosts: workers
  tasks: 
    - name: "Get Hostname of Workers"
      block:
      - command: "hostname"
        register: hostname

      - debug:
          msg: "Hostname: {{ hostname.stdout }}"