---
- hosts: rpis
  gather_facts: yes
  become: yes
  roles:
    - "raspbian"
    - "k3s/download"

- hosts: master
  become: yes
  roles:
    - "k3s/master"

- hosts: workers
  become: yes
  roles:
    - "k3s/worker"